### ISSUE TITLE
问题

### ISSUE THREAD

**Issue by zjh299** [Li-Qingyun/RSCoTr#10]
我使用python tools/train.py configs/multi/MTL_swin-t-p4-w7_1x1_dior.py --load-task-pretrain --work-dir work_dirs/MTL_swin-t-p4-w7_1x1_dior这个命令出现下面的报错：(rscotr) zjh@yhp-PowerEdge-R740:~/RSCOTR$ python tools/train.py configs/multi/MTL_swin-t-p4-w7_1x1_dior.py --load-task-pretrain --work-dir work_dirs/MTL_swin-t-p4-w7_1x1_dior
Traceback (most recent call last):
  File "/home/zjh/anaconda3/envs/rscotr/lib/python3.8/site-packages/mmcv/utils/config.py", line 103, in _validate_py_syntax
    ast.parse(content)
  File "/home/zjh/anaconda3/envs/rscotr/lib/python3.8/ast.py", line 47, in parse
    return compile(source, filename, mode, flags,
  File "<unknown>", line 11
    type='MTL',.
               ^
SyntaxError: invalid syntax

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "tools/train.py", line 252, in <module>
    main()
  File "tools/train.py", line 122, in main
    cfg = Config.fromfile(args.config)
  File "/home/zjh/anaconda3/envs/rscotr/lib/python3.8/site-packages/mmcv/utils/config.py", line 340, in fromfile
    cfg_dict, cfg_text = Config._file2dict(filename,
  File "/home/zjh/anaconda3/envs/rscotr/lib/python3.8/site-packages/mmcv/utils/config.py", line 252, in _file2dict
    _cfg_dict, _cfg_text = Config._file2dict(osp.join(cfg_dir, f))
  File "/home/zjh/anaconda3/envs/rscotr/lib/python3.8/site-packages/mmcv/utils/config.py", line 207, in _file2dict
    Config._validate_py_syntax(filename)
  File "/home/zjh/anaconda3/envs/rscotr/lib/python3.8/site-packages/mmcv/utils/config.py", line 105, in _validate_py_syntax
    raise SyntaxError('There are syntax errors in config '
SyntaxError: There are syntax errors in config file /home/zjh/RSCOTR/configs/multi/MTL_swin-t-p4-w7_1x1_resisc&dior&potsdam.py: invalid syntax (<unknown>, line 11)
Exception ignored in: <function _TemporaryFileCloser.__del__ at 0x7f0a2c2a0b80>
Traceback (most recent call last):
  File "/home/zjh/anaconda3/envs/rscotr/lib/python3.8/tempfile.py", line 456, in __del__
    self.close()
  File "/home/zjh/anaconda3/envs/rscotr/lib/python3.8/tempfile.py", line 452, in close
    unlink(self.name)
FileNotFoundError: [Errno 2] No such file or directory: '/tmp/tmppwngnu6u/tmpo1sizzkt.py'请问怎么改呢，是不是
![image](https://github.com/user-attachments/assets/e644f211-3ffb-4238-9d15-cbc89364d443)
zhe'g这个MODEL需要变化，请问要怎么改呢

**Comment by Li-Qingyun** [comment]
那不多一个句号吗？
